---
name: 'issue-metrics-with-users'
author: 'lawang24'
description: 'A GitHub Action to report out issue metrics with user aggreagations'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-square'
  color: 'white'
